vcs: git

prerequisites:
 - working-copy-check
 - display-last-changes
 - tests-check


pre-release-actions:
    composer-update: ~
    changelog-update:
        format: semantic
        dump-commits: true
    vcs-commit: ~

version-persister: vcs-tag
version-generator: semantic

post-release-actions:
    vcs-publish:
        ask-confirmation: true
